version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: task-db
    restart: always
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
